### ISSUE TITLE
Fresh install, no QR code.

### ISSUE THREAD

**Issue by GaryLittlemore** [Geektoolkit/DynaframeProIssues#11]
I completed a fresh install yesterday, on boot I didn't get a qr code as stated in the install notes. Has something changed that's not been updated in the 'how to' install instructions?

**Comment by bdlou** [comment]
Did you have a network cable plugged in to the unit? That will bypass that step. If not, if you plug a keyboard in and press I, does it show that you have an IP address?

**Comment by GaryLittlemore** [comment]
Thanks bdlou, yes I had a network cable connected. That explains that.
