### ISSUE TITLE
Unable to see desktop via VNC, sizing is all messed up?

### ISSUE THREAD

**Issue by arretx** [Geektoolkit/DynaframeProIssues#17]
Upon my first boot, I used VNC to access the Pi and I get a very small screen in portrait mode.  If I hit escape, I see the Dynaframe wall paper, but I can't navigate any part of the Pi GUI with much success.  I installed the image while connected to Ethernet and now I need to configure WIFI, but using raspi-config doesn't seem to create a successful configuration.  I get no DHCP response for the mac address on the Pi.

How do I login with VNC and see my Pi desktop in full?

**Comment by arretx** [comment]
Never mind.  I got it.  It seems that I still needed to use the WIFI transmitted by the Pi to configure the WIFI correctly.

**Comment by bdlou** [comment]
@arretx Regarding the Desktop UI, if you're running an alpha, it appears that if you do a Shift-U while Dynaframe is running, we run a command to enabled the Taskbar UI.  And then to hide it again, when Dynaframe is running Ctrl-U will do it.  Hope this helps!
