### ISSUE TITLE
Screen Resolution Mismatch

### ISSUE THREAD

**Issue by drv55** [Geektoolkit/DynaframeProIssues#19]
I've noticed that my photos are distorted (stretched vertically). After some investigation, I found that there is a mismatch between the RPi display output resolution (1920 x 1080 = 1.8 aspect ratio) and my computer monitor display resolution (1920 x 1200 = 1.6 aspect ratio). The photo distortion I am seeing (original = 1.5 versus distorted = 1.35) matches the display mismatch (1.8 / 1.6 = 1.5 / 1.35). How do I fix this?

**Comment by drv55** [comment]
Cancel this request. After some additional investigation I realized that my application of Dynaframe will use 1080p TV monitors which matches the RPi display output resolution (1920 x 1080). The computer monitor (1920 x 1200) was just a temporary display I was using to get familiar with Dynaframe. So I've replaced it with a small TV monitor and it's working fine with no image distortion.

**Comment by bdlou** [comment]
Sorry for the delay. I've been down sick. If you do decide to you a non-1920x1080 monitor, you should be able to break out into a terminal, run sudo raspi-config, and change the resolution options within there. Glad you got things going!

**Comment by qwksilver** [comment]
Closed, glad you got it fixed!
