### ISSUE TITLE
Question - Infobar Setting / Image Info field? 

### ISSUE THREAD

**Issue by drv55** [Geektoolkit/DynaframeProIssues#20]
One question I have concerns the Infobar Setting / Image Info field? I assume this is an EXIF field? Which one?

**Comment by bdlou** [comment]
This functionality will be getting a major overhaul in the coming months. We want to figure out a way to expose all of the EXIF fields and allow you to choose what you want to display. For now, it's using the following (which is most likely why you're not seeing anything):

Windows XP Title, Windows XP Author, Windows XP, Windows XP Keywords

**Comment by Poncije** [comment]
Meaning you can only edit them on Windows XP?

**Comment by bdlou** [comment]
> 

No, meaning that those are the only hard coded fields that are exposed at this time.  The feature will be redone in a way where we will provide a UI to choose which EXIF fields you want to display.

**Comment by ajw2060** [comment]
The ExifTool may be of use to set the EXIF data in your images.
https://exiftool.org/
I have used it an found it one of the better options for setting or inserting missing EXIF data.  It allows setting or insertion of the various "XP..." tags - you do not have to just use Windows File Explorer | Properties.  One of the useful features is that it shows the proper name for the EXIF tag as well as the displayed name.  Sometimes these are different - notably the XP names.  Maybe Joe will consider adding ExifTool to the baseline image as a useful diagnostic tool on DynaFramePro.

**Comment by bdlou** [comment]
For all EXIF related usage, please move over to using the new Overlay system.  We should have a new release out soon that addresses some issues that the April release had with Overlays, and we will be exposing a ton of EXIF tag options for you to personalize your experience with.

**Comment by Geektoolkit** [comment]
closing this. the overlay system is where we should do all of this work and it's MUCH more robust than the infobar for this type of usage
