### ISSUE TITLE
Fix or Evolution - Pause button

### ISSUE THREAD

**Issue by vmonichon** [Geektoolkit/DynaframeProIssues#21]
When I press the pause button, I can't see any difference between the slideshow being in Pause mode or not. Is there a way to see what's the status?

My apologies if it is available somewhere and I missed it.

Fix: Change the Pause button appearance or write the status somewhere
Proposal : Maybe this could be something where the button switch from Pause to Play and Play to Pause...

PS: Amazing piece of software that you have created!

**Comment by bdlou** [comment]
Thank you for the kind words!  Yes, this one has annoyed me for a while.  It's on my radar.  There are a couple things here.  The pause button in the web UI needs to be reflective of the pause state.  This will require us to check the system for pause state, so it's a little tricky to implement, but shouldn't be too bad.  The other is we've discussed visual feedback on screen.  So potentially a pause icon that fades out after showing up briefly to show that the action has taken place.  We will look to address this in the coming months.

**Comment by vmonichon** [comment]
That sounds awesome! The visual feedback on the screen is a cool idea, would be worth even to be permanently on the infobar.

Thnks again.

**Comment by bdlou** [comment]
This is fixed in the next release of the new web UI
