### ISSUE TITLE
Suggestion: Remote Share library

### ISSUE THREAD

**Issue by vmonichon** [Geektoolkit/DynaframeProIssues#22]
Within a household with techies, you will always find somebody having pictures already organized and store somewhere, may it be a Synology, a Mac, or an Unraid Server,...

In the end, it could be interesting for the user to just point the frame to the local network location potentially via different protocols:

SMB/CIFS
FTP
...

Then what would need to be determined is how to handle a share becoming unavailable. Automatic reconnection when available?

**Comment by bdlou** [comment]
We already have an existing internal work item tracking this suggestion.  Thanks!

**Comment by vmonichon** [comment]
I knew I couldn't be the first to think it ;) But for the commercial version that could be a plus. Thks for the quick answer.

**Comment by qwksilver** [comment]
I will add to this that our internal work items are related to using our Web/Phone UI to set these things up.  With ssh, vnc, or a keyboard and mouse attached, there are any number of guides out there to setup using NFS, SMB, and so on to access remote locations on your lan for files.  There are also discussions over on discord for alll that and a final option of setting up rcopy -sync to clone your remote folders in dropbox, gdrive, onedrive, etc and run those photos collections.

A usb stick, or drive, will just attach, and show up in your playlist (may need a reboot to work well).  You may also need to layout the stick as a list of folders with pictures under those, and not just all the photos on the main folder of the stick, for best results and control anyway.

There is also a samba share available to your network, at \\<dynaframe ip address>\media, you can add folders, and fill them with photos, and they will show up in your frame playlists.  This is also a way to manage your uploads if you need to remove a lot of items that you have uploaded.  (warning here: no trash cans in dynaframe, anything you delete from there, please have your original copies elsewhere.)

Anyway right now, network files are super doable, just not super user friendly, YET!

**Comment by vmonichon** [comment]
Yes, you are right I could do a CIFS mount point, this would definitely work.
So just, I understand if it becomes unavailable, what would be the behavior of the app?

Thanks for taking the time to answer me. really appreciate.

**Comment by qwksilver** [comment]
typically i create a connection to a windows 10 box called:
/home/pi/dfl
in that i have 1kp 4kp 1kl 4kl testp testl and so on
so on my portrait frame then on the playlist screen i will add two items:
`/home/pi/dfl/1kp`
`/home/pi/dfl/testp`

it will look like this:
![image](https://user-images.githubusercontent.com/20508309/207763513-a45cac2f-22c5-48cc-8029-046f91e615dd.png)

from there you get switches
for home automation you can send curls like these two:
*1 `http://<dynaframe ip address>/command/?COMMAND=ADDSUBDIRECTORY&VALUE=/home/pi/dfl/1kp/photos`
*2 `http://<dynaframe ip address>/command/?COMMAND=ADDSUBDIRECTORY&VALUE=/home/pi/dfl/1kp`
in case 1, it will turn on that item photos
in case 2, it will turn on all items in 1kp
to reverse and turn off replace ADDSUBDIRECTORY with REMOVESUBDIRECTORY

there is also a seperate api command that will turn on or off all items in all locations
which are: `?COMMAND=playlistallon  (or off)

If the share is missing, those files are ignored, when they reappear they get cycled back in
there are things you can enable like Wait for network on boot.
if you are a more advanced linux user ask me over on discord how to get to examples of file share connections via systemd
but that is not strictly needed.
