### ISSUE TITLE
Information: Raspi 3B versus Raspi 3B+

### ISSUE THREAD

**Issue by mattvirus** [Geektoolkit/DynaframeProIssues#23]
Apologies for opening issue - couldn't find specific information regarding this question.

3B+ is roughly same as the 3B, other than 200mhz cpu speed and having AC wifi.  Any reason the 3B isn't listed as compatible versus the 3B+ being on the approved list?

**Comment by qwksilver** [comment]
Many people have implemented the 3b, our current understanding is that it has issues with videos, but does fairly well for playback of photos that are the same or nearly the screens resolution.  Feel free to fire one up, and join us on discord for discussion of how it's going.

**Comment by Geektoolkit** [comment]
Closing this one. The supported list on the patreon needs to be updated as well as a new YT video discussing the versions.
