### ISSUE TITLE
Overlays - Usability suggestion for text locations

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#26]
This relates to Build 821e376.  The usability of the Overlays screen in the web interface could be improved by the following changes.

1) Move the "Horizontal Alignment" and "Vertical Alignment" controls up the page so they appear before the various "Margin ..." settings.  The Alignments are the basic location of the overlay item and the Margins are a minor tweak to the positioning so it makes sense to put the more significant control higher up the page.  It may even be possible to only display the Margin settings relevant to the Alignment.  For example an item laid out on the bottom left corner probably only needs the "Margin (Left)" and the "Margin (Bottom)" settings.  The other do not appear to be relevant.

**Comment by Geektoolkit** [comment]
The Location portion is Fixed, will be in next alpha.  Good feadback.   The filtering of Margin bottom left and such for left I'm going to leave as is for now as the matrix of possabilities gets a bit tedious.  If we get alot of feedback that it's confusing though we'll dynamically adjust those then.
