### ISSUE TITLE
Display EXIF location data

### ISSUE THREAD

**Issue by Nancy-Robertson** [Geektoolkit/DynaframeProIssues#3]
Preferably translating the coordinates into something that is human readable.

**Comment by Geektoolkit** [comment]
Great suggestion. Starting this work, I've incorporated a translation API internally that will translate from long/lat to 'nearest city'.  Currently supports cities with a population over 1000

**Comment by coolinx** [comment]
Question: You say; Currently supports cities with a population over 1000

So every city world wide with a population over 1000 is included?

**Comment by Geektoolkit** [comment]
According to the database I'm using, yep! If you have a coordinate for me to try I can tell you what city it returns

**Comment by coolinx** [comment]
Made a picture with an iPhone which has this in the Exif data:
Latitude 21; 20; 19.1999999999970328
Longitude 34; 42; 56.3999999999943213
Altitude 86.0791556728232194

That [should be this location](https://www.google.com/maps/place/21%C2%B020'19.2%22S+34%C2%B042'56.4%22E/@-21.3386667,34.713478,942m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x9d4f2f811eee4cbd!8m2!3d-21.3386667!4d34.7156667).

**Comment by Geektoolkit** [comment]
Hmm, that was a good test. The closest city if I'm seeing right is Govura, with a population of 34,000 according to wikipedia. I'm getting back "Beira, MZ" with the current api 

Helpers.MiscHelpers.GetCityFromCoordinate(-21.201999999,34.4256399999)
"Beira,MZ"

I have another database I can try to see if it gets a more correct location.  
So far it is about 100 miles off. We may have to live with a bit of an error and then work to dial things in.

**Comment by coolinx** [comment]
Yes, so for that picture the iPhone also returns Govura as location.
So you have an offline database you query to get the nearest city, right?
Why not perform an on-line query to google or whatever other service that can return much more accurate location information for even the most remote locations around the globe?

**Comment by Geektoolkit** [comment]
Online services usually require an API key, have a rate limit, and or cost. I'm trying to find the most user friendly way to pull it off and not have users have to go snag API keys or pay. Also one of the things that really sets Dynaframe apart is there is no reliance on the cloud. The entire device works offline.

That being said I will see if I can design it to be flexible so that advanced users can put in API keys for a service and others can use it offline.

**Comment by Geektoolkit** [comment]
Update on this: We will be reworking the 'infobar' in November and during that we'll address this. We have the API for location working locally without needing an online service, and will work to dial it in.

**Comment by Geektoolkit** [comment]
This is in the latest beta, and will be in the next release. Please let us know if it's working solid for you and if not feel free to reopen this with feedback
