### ISSUE TITLE
Overlays - Add user defined name to each control

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#30]
This relates to Build 821e376.

Would it be possible to add a user defined unique name to each overlay field?  At present the only unique identifier appears to be the number in parenthesis appended to the control type (such as Exif(2)).  This makes it difficult to remember which control is which when you have several displayed.  (I use EXIF title, date, author and hope to use location as well as a couple static text fields).  Some kind of user defined name associated with each control would be useful as the "Select Item" index.

**Comment by Geektoolkit** [comment]
Yes absolutely.  I was thinking of putting the current value in if possible.  I'll look into where these would have to go. We definitely have to have some kind of sanity added here...when I added 12 exif datas recently it was a bit nuts figuring out which was which :)

**Comment by Geektoolkit** [comment]
This will be in the next update. Great suggestion (and using it I'm so much happier when dealing with complex overlays)

**Comment by Geektoolkit** [comment]
This has shipped, closing it out
