### ISSUE TITLE
Overlays - Text Box alignment

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#31]
This relates to Build 821e376.

The text boxes shown on the Overlays page do not line up.  Depending on the control type selected (text, exif, date/time), one or more rows of controls will be presented that are specific to this control type, followed by font, colour and location settings that are common to all controls.  The top set of controls appears to be independently scrollable (which may not be needed) and the text boxes appear to be right justified whereas the text boxes in the lower section appear to be left justified.  On wider screens the top group of text boxes is way off to the right.  At a screen width of 880 the controls line up, but when narrower or wider the top couple text boxes a re mis-aligned with the bottom ones.

**Comment by Geektoolkit** [comment]
Thankyou this is great feedback, and I'll take a look in the April bugfix for fixes such as this.

**Comment by Geektoolkit** [comment]
April we're looking at cleaning up the work that was just put in, and this is the kinds of bugs I want to tackle. Putting this on consider for the next bugfixes that go in

**Comment by Geektoolkit** [comment]
This should be resolved for the next release. I did a bunch of cleanup of the Overlay Ui to simplify it and align the textboxes as well as the tooltips

**Comment by Geektoolkit** [comment]
Fix checked in, please reopen if other issues show with alignment. Please also let me know if it's on a phone/tablet etc. as that'll help me know which 'snap' to look at for alignment (each sized device uses a bit differnet css)
