### ISSUE TITLE
Overlays - Text wrapper option

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#32]
This relates to Build 821e376.

Would it be possible to add a "text wrapper" around selected controls.  For example, I would like to display something like "Image contributed by" in front of the EXIF author field, or "Today is" in front of the clock control.  I realise this can be achieved using simple text and managing the margin offsets, however this is not so great when the field is right aligned and of variable length.  A "wrapper" would make the text plus the control all into one element with common font and colour settings.  Ideally the text wrapper could prepend as well as append text.

**Comment by Geektoolkit** [comment]
This sounds like a great feature, and shouldnt be hard to implement. Putting it on the todo list and figuring out where we can get it implemented

**Comment by Geektoolkit** [comment]
Prepend will be in the next release. i'll see if I can quickly add append as well since I have the basic logic in there for adding extra text.

**Comment by Geektoolkit** [comment]
Postfix will also make it into next release

**Comment by Geektoolkit** [comment]
Feature added, will be in next release! Thanks for the suggestion!
