### ISSUE TITLE
Overlays - bug in "Edit Overlay" functionality

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#35]
This relates to build d2db213.

When trying to edit an existing overlay, the various properties of the selected overlay item do not all display correctly.  This applies only to EXIF type fields.  When an existing EXIF item is selected for edit, the properties such as font size, foreground color and positions all update to reflect the previously set values.  However the "Exif Tag" drop down always shows "Image Width" regardless of what tag was previously configured for this item.  The actual JSON file has the correct data, but it does not get taken from the file into the UI.

This UI may be more intuitive if it used a "SAVE" button to save all changes to the overlay item after the various changes are made.  At present it seems some of the properties are save as they are changed, but this is not intuitively clear.

**Comment by Geektoolkit** [comment]
Good bug, I'll add it to my overlay work. Assigning to me.

**Comment by Geektoolkit** [comment]
Please let me know if you're still seeing this, in the Sept. build I'm no longer seeing this and believe it was resolved.
