### ISSUE TITLE
Config launch page - No focus indication - March release

### ISSUE THREAD

**Issue by xkcd42** [Geektoolkit/DynaframeProIssues#37]
On the new config landing page there was no indication of which field was in focus as I tabbed through.

**Comment by bdlou** [comment]
This is great feedback.  Thank you.  We will need to do some work to make a custom focus indicator.

**Comment by Geektoolkit** [comment]
Adding note to consider for April

**Comment by Geektoolkit** [comment]
This will be fixed in the April release

**Comment by Geektoolkit** [comment]
Fixed. Fix is in beta. Please reopen if you hit issues.
