### ISSUE TITLE
Feature Request: API to allow shell or bash script to be executed.

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#39]
Background:
I want to use the Dynaframe as my screen saver on HDMI1 for my TV that uses the FireTV stick on HDMI4.  I am using Home Assistant to watch that when the FireTV stick goes into Standby mode I manually have to call a CEC Client command on the Dynaframe to get the TV to switch to HDMI1 to show the Dynaframe slide show.

Feature Request.
I would like the current Dynaframe API to have a section where I could expose a custom GET command. 
ex: http://10.0.0.1/command/?CUSTOMCOMMAND=[USER_SPECIFIED_CMD_NAME]
http://10.0.0.1/command/?CUSTOMCOMMAND=CED_AS_CMD.

On the Dynaframe API custom commands could be a separate thing to not conflict with Dynaframe's own API.
Form inputs:
- Command Name: 40 nvarchar (ex: CEC_AS_CMD)
- Command or Script: 200 nvarchar to directly enter the command or point to the .sh file to run.  My command is 'sudo echo as | cec-client -s -d 1'
- Response would just be exist code.

Future, this could provide a very powerful utility for users to get additional features for our own edge causes that the Dynaframe team shouldn't have to own/support for all clients.

I don't fully understand the limitations of the Dynaframe tools so this ask could be too big

**Comment by Geektoolkit** [comment]
It's a good feature request and we will think on a good design for it. One huge challenge is that if there is a device on your network that can take a command over http and run that at root....it's quite a security hole so to speak. I'll think on a way to do this securely, or at least in a manner where the user will know they're doing something dangerous. One possibility is to have it restricted by which ips can send the command, or a pass phrase as part of the command

**Comment by jcrowegitHu8** [comment]
The custom API portion of the UI should require an admin set of credentials
to be setup. As that's the side you're willingly setup a very specific sudo
command. You can then set you whitelist of calling IPs.

This doesn't add complexity as you'll need to include the headers in the
GET request. That's you'll be checking. Source, origin, or a custom header.

Longer term using a JWT would be best but that has a lot more work of
adding an auth provider.


To simply this request maybe we just optionally add the cec client 'as'
command when the screen on command is fired.  And 'is' command would be for
screen off. The option would be a checkbox in the UI.

**Comment by qwksilver** [comment]
all of these things can be accomplished already with plink(windows) which will issue commands to the ssh server built into pi, we will likely build a direct api to address the OS when the feature is already there.  I use it almost daily and found i could get the info i need pretty quick from google searches on sending remote commands and scripts to pi.

there are also ways, behind ssh keys and/or simple passwords, also through plink, to send elevated commands

@Geektoolkit recommending close this issue as feature already present in os
