### ISSUE TITLE
Display EXIF Date photo taken

### ISSUE THREAD

**Issue by Nancy-Robertson** [Geektoolkit/DynaframeProIssues#4]
For those of us that use Dynaframe to display family photos, seeing the date a particular photo was taken is a very nice to have feature.

**Comment by Geektoolkit** [comment]
Adding infobar tag. This needs to be applies there.

**Comment by Geektoolkit** [comment]
Update: As part of our overlay work for November we'll be addressing this.

**Comment by Geektoolkit** [comment]
This is in the latest beta, and will be in the next release
