### ISSUE TITLE
Usability: Improve Mobile UI - Grids/Tables

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#41]
In the April re-release  I noticed the mobile UI has worsened.  I primarily use my android phone and firefox browsers for the Dynaframe web UI. (see attached image of bad mobile user experience)

**General High Level ask:**
Please improve mobile grid response points to allow for labels and buttons to be seen so that only vertical scrolling is required.

**One Possible Solution:**
You could setup the labels and the controls to stack on top of each other so that they can take up the available width of the mobile device in it's vertical orientation.  You would still notice the rows by the row outline and alternating colors, so you don't go scroll

![Screenshot_20230414_073311_Firefox](https://user-images.githubusercontent.com/17546577/232052737-dedde5a8-9e7c-485d-b707-1cefca71c937.jpg)
 blind.

**Current Environment:**
UpTime: 0.00:51:09, Temp: 61.604 C, Memory: 169 mb, Resolution: 1920 x 1080
Database items: NYI, Drive space: /: 47.97 GB/58.24 GB, Automatic Mode: True
Build: 958d92a, Model: Raspberry Pi 2 Model B Rev 1.1

**Comment by Geektoolkit** [comment]
Please let me know if the latest release fixes this for you. I did a lot of work around the mobile UI to fix this up

**Comment by jcrowegitHu8** [comment]
Confirmed June release looks great.  Please close this issue.

Build: 620dbec, Model: Raspberry Pi 2 Model B Rev 1.1
![Screenshot_20230714_101944_Firefox](https://github.com/Geektoolkit/DynaframeProIssues/assets/17546577/4c0d4091-8b72-4a7f-bb4c-b853bf9e0865)
