### ISSUE TITLE
Bug - Low Priority: Mobile UI Navigation Won't Collapse. 

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#42]
**Mobile Device:**
Android
**Browser:** 
Firefox

When using the hamburger menu from Android Firefox browsers.  I get get the menu to expand but the screen flickers and won't collapse back down.  It's just causes me to have to scroll down past the menu to get to the screen.

**Current Environment:**
UpTime: 0.00:51:09, Temp: 61.604 C, Memory: 169 mb, Resolution: 1920 x 1080
Database items: NYI, Drive space: /: 47.97 GB/58.24 GB, Automatic Mode: True
Build: 958d92a, Model: Raspberry Pi 2 Model B Rev 1.1

**Comment by bdlou** [comment]
This is addressed with the new web UI
