### ISSUE TITLE
Bug | Usability : Navigation is Inconsistent

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#43]
In the April release the navigation menu shows different options depending on what page you are on.

Expectation:
Regardless of what page I'm on the menu has a consistent state. 
Meaning:
1)The same menu items are always shown regardless of page.
2)This is not accounting for sub-menus or if dynaframe supports permissions for different users.

**Test Environment**
Computer: Windows10
Browser: FireFox

**Current Environment:**
UpTime: 0.00:51:09, Temp: 61.604 C, Memory: 169 mb, Resolution: 1920 x 1080
Database items: NYI, Drive space: /: 47.97 GB/58.24 GB, Automatic Mode: True
Build: 958d92a, Model: Raspberry Pi 2 Model B Rev 1.1

### Example1: /Dynaframe/Playlist.html

![nav2](https://user-images.githubusercontent.com/17546577/232056210-1e743762-0b9f-463f-87d6-d412e0505804.PNG)

### Example2: /Dynaframe/index.html
![nav1](https://user-images.githubusercontent.com/17546577/232056258-2fbd0640-6151-47fa-9850-0b8a4774afd3.PNG)

**Comment by Geektoolkit** [comment]
I'm not seeing this in recent versions, and believe this to be fixed. We switched that menu to be a single file that all pages load to keep it consistent now. Good bug/catch!

Note; I do expect in the future this will be rewritten entirely to use a much nicer control scheme (nested submenus). For now this is where it's at, but it should be consistent in the Sept and later builds.
