### ISSUE TITLE
Bug | Functionality - MOV movie files still continue to break Dynaframe desktop UI

### ISSUE THREAD

**Issue by jcrowegitHu8** [Geektoolkit/DynaframeProIssues#44]
This bug has existed since the December release and continues into the April release.  

**Observed behavior:**
Any MOV file I try to play will cause the display to show a black screen.  From the "/Dynaframe/Debugging.html" I can see that the frame is stuck on that MOV file indefinitely.

**Speculation of Issue:**
I believe that the app is unable to play the MOV and an error is occurring.  

**Short-Term Proposed Fix:**
I would like Dynaframe to be more resilient at checking for an error playing a video and to recover and move on to showing the next video.  Perhaps this could be a toggleable feature.  "Try to Recover On Errors".  This way we can test the issue and see logs.  But for end users like myself we just move on with life.  As I expect there will be many file formats Dyanframe can't play over the years ;)

**Long-Term Proposed Fix:**
I would like Dynaframe to actually support playing the MOV files as VLC player can play all of my videos.  So I'm not really sure why this doesn't work in the current April release.

**User Background:**
My primary use of Dynaframe is showing family videos so many of the older videos will be MOV files.  Currently I have them all archived in a single folder called MOV since I know they break Dynaframe and force me to have to reboot.

**Current Environment:**
UpTime: 0.00:51:09, Temp: 61.604 C, Memory: 169 mb, Resolution: 1920 x 1080
Database items: NYI, Drive space: /: 47.97 GB/58.24 GB, Automatic Mode: True
Build: 958d92a, Model: Raspberry Pi 2 Model B Rev 1.1

**Comment by bdlou** [comment]
When you say "VLC player can play all of my videos", are you referring to the inbox VLC on the Raspberry Pi 2 itself?  Dynaframe is using VLC for video playback, so if it won't play in us, it typically won't play in the VLC inbox.  If you're breaking out into the OS and are able to play a failing video in VLC, then we'd need a sample video to be able to troubleshoot this, as I've played many MOV files I've downloaded from the early days and they are playing.

**Comment by jcrowegitHu8** [comment]
Admittedly I only tested playing the MOV files from my Windows machine before uploading them to the Dynaframe SMB share.  I'm trying to test out playing the MOV files directly from VLC player on the Dynaframe-PI.  

What is the preferred way of getting the PI to boot without dynaframe blocking the desktop?

Note:
![image](https://github.com/Geektoolkit/DynaframeProIssues/assets/17546577/7404a7c7-4e57-4fcb-b470-67db807a16b8)

**Comment by bdlou** [comment]
H265 is not supported on a Raspberry Pi 2:
https://forums.raspberrypi.com//viewtopic.php?p=683295#p683295

They will possibly struggle or resource constrain a Pi4 as well, though
they may squeak by due to being 1080p.

If you'd like to test it, when Dynaframe loads simply press ESC on an
attached keyboard and then launch VLC from the Raspberry Pi menu.

**Comment by Geektoolkit** [comment]
One thing to note is we do try to detect decoding failures, however we require VLC to tell us that it can't handle a file. As much as I'd love to say that VLC does a bang up job at this, it's sadly not the case. Without reliable communication from VLC it becomes very hard to have any kind of useful mitigation when this happens.

I'll be very curious what you get when you try to view it using the built in VLC player on a pi2.  Another fun thing to know is that video decoding is heavily based on CPU/GPU features.  So while your windows machine likely has a card that can easily decode in hadware most of what you throw at it (and likely so can your phone) the pi's CPU/GPUs can be a bit..limited.

That all being said, we're learning and working to improve this and want a better experience.  Maybe that involves a feature that interrogates video files for the codecs and then skips them by default or something and logs warnings to prevent even trying to play them.  We'll discuss and figure out a solution.
 
Please let us know what the pi does when you try to play the file directly.

**Comment by jcrowegitHu8** [comment]
**Update:**
The PI would not play the MOV file directly via VLC either.

**Workaround:**
I googled a way to use VLC play's GUI to convert MOV files to mp4 and then my Dynaframe-pi was able to play them.  There are command line options to do this as well.

**Background on my problem:**
These videos originally came from my wife's iPhone.  When they auto backup to Synology NAS they get converged to MOV, as it's a more playable format than the native HEIC (or w/e).

Let's go ahead and close this issue and we can open a new one.  I would like the feature of just telling dynaframe what video's to play.  I think that makes the most sense of the product as a whole as each PI or other hardware will be able to support different video formats.  I just want to make sure the product evolves to support a wider base.  As I'm doing an old pi2 as all my other hardware is used.

Thanks team, please confirm that you want me to open a new issue for the feature request.

**Comment by bdlou** [comment]
In the next update, all videos using the VP9 or HEVC codecs will be skipped if they are in a playlist, so this issue will go away.  The Pi cannot handle these codecs.
