### ISSUE TITLE
Overlays - Request to sort EXIF tags alphabetically

### ISSUE THREAD

**Issue by ajw2060** [Geektoolkit/DynaframeProIssues#55]
This is observed in build 620dbec.

The Overlay Designer page offers many EXIF tags for use in the custom overlays.  These EXIF items do not appear to be sorted in any particular order in the "EXIF Tag" dropdown box.  Could these be sorted alphabetically so it is easy to find items such as "Title".

**Comment by Geektoolkit** [comment]
I was dreading this...its such a huge list and that was going to be quite the task. Turns out AI could do it for me. It'll be alphabetized in the next release :)
