### ISSUE TITLE
Experimental: Show Internet Image File url only accepts image extention

### ISSUE THREAD

**Issue by coolinx** [Geektoolkit/DynaframeProIssues#6]
build 94ddfd0
On the Experimental page in the field behind the button "Show Internet Image File" only accepts an url that ends with an image extention like .jpg, .png, etc. Better would be to accept any url.

I personally would need this to get automations working where Home Assistant sends via the API the url of an album image playing on Spotify. An example of such url is this one from the Home assistant media_player entity attribute called entity_picture. 
http://hass.local:8123/api/media_player_proxy/media_player.unnamed_room?token=18c824911579c9bf8c5209ca0b16de81d547007ab0da6627ba244003b5cb7ed5&cache=4166e4f23b305e06

**Comment by Geektoolkit** [comment]
we will have to see if the engine is smart enough to load an image without an extension and figure out what it is. If not we'll have to proxy/cache the image and use the headers to determine the mimetype. Good issue/scenario, we'll look into it.

**Comment by bdlou** [comment]
@coolinx I have checked in a fix for this.  It will be available in the next Alpha.  Thank you for your feedback!

**Comment by qwksilver** [comment]
alpha released see discord, feel free to test and give feedback here

**Comment by coolinx** [comment]
Nice to see this was getting some attention. It could open the door to nice automations in Home Assistant, for example that pass image url's to the frame to display current playing album art from Spotify.
Unfortunately I can't test this any time soon.

**Comment by bdlou** [comment]
Closing this as fixed.  Please create a new issue with a publicly available repro if you encounter any issues.  Thanks!
