### ISSUE TITLE
Media FIle Permissions

### ISSUE THREAD

**Issue by dougharvey51** [Geektoolkit/DynaframeProIssues#8]
When using the web interface to create playlist directories and upload files, the files and folders are owned by root with permissions 755.  This means someone using the samba share (as guest) can not add or delete files in those directories.  If using the samba share exclusively, this is not a problem, but the permissions do not allow complete mixed use of methods of playlist management.
I discovered this while building a Mac Applescript utility that syncs an album from the Photos application of MacOS to the DynaFrame.
(it uses keywords associated with each image to place images in playlist folders on DynaFrame)

**Comment by qwksilver** [comment]
share permissions were improved, open new issue if there are still problems, i think implemented in SEP, but are definitely in with DEC image.
